#!/bin/csh
#$ -N helix6
#$ -j y

setenv MPSIM_DATA /home/ravi/GEnsemble/programs/mpsim/mpsimdata
/home/ravi/GEnsemble/programs/mpsim/mpsim helix6.3.50_K.ctl > helix6.3.50_K.out
/home/ravi/GEnsemble/programs/mpsim/mpsim helix6.3.100_K.ctl > helix6.3.100_K.out
/home/ravi/GEnsemble/programs/mpsim/mpsim helix6.3.150_K.ctl > helix6.3.150_K.out
/home/ravi/GEnsemble/programs/mpsim/mpsim helix6.3.200_K.ctl > helix6.3.200_K.out
/home/ravi/GEnsemble/programs/mpsim/mpsim helix6.3.250_K.ctl > helix6.3.250_K.out

cp helix6.3.250_K.fin.bgf helix6.4.pre_dynamics.bgf

/home/ravi/GEnsemble/programs/mpsim/mpsim -s5000 helix6.5.dynamics.ctl  > helix6.5.dynamics.out
/home/ravi/GEnsemble/programs/utilities/snapgz2bgf.pl -s 'helix6.5.dynamics.snap*' -t helix6.4.pre_dynamics.bgf --skip 254999 >& helix6.5.dynamics.eng
/home/ravi/GEnsemble/programs/utilities/bgf_snap_rmsd -m -v -t helix6.4.pre_dynamics.bgf helix6.5.dynamics.snap254999 5000 150 > helix6.5.dynamics.rmsd
/home/ravi/GEnsemble/programs/utilities/bgf_match.pl -p helix6.5.dynamics.snap -f 254999 -i 5000 -n 150

mkdir helix6.3.warmup
mv helix6.3.*.* helix6.3.warmup
gzip -r helix6.3.warmup

mkdir helix6.5.dynamics.bgfs
/home/ravi/GEnsemble/programs/utilities/multi_bgf2pdb.pl helix6.5.dynamics.snap*.bgf
mv *.bgf helix6.5.dynamics.bgfs

mkdir helix6.5.dynamics.pdbs
mv *.pdb helix6.5.dynamics.pdbs
gzip -r helix6.5.dynamics.pdbs

mkdir helix6.5.dynamics.snaps
mv *.snap* helix6.5.dynamics.snaps
gzip -r helix6.5.dynamics.snaps

gzip helix6.5.dynamics.ctl
gzip helix6.5.dynamics.traj1
gzip helix6.5.dynamics.rst
gzip helix6.5.dynamics.out
touch _dyn_finished_

