/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.19
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON

#ifdef __cplusplus
template<class T> class SwigValueWrapper {
    T *tt;
public:
    inline SwigValueWrapper() : tt(0) { }
    inline ~SwigValueWrapper() { if (tt) delete tt; } 
    inline SwigValueWrapper& operator=(const T& t) { tt = new T(t); return *this; }
    inline operator T&() const { return *tt; }
    inline T *operator&() { return tt; }
};                                                    
#endif


#include "Python.h"

/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#                       define SWIGIMPORT(a) extern a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#                       define SWIGIMPORT(a) extern a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#                       define SWIGIMPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#                       define SWIGIMPORT(a) a
#               endif
#       endif
#else
#       define SWIGEXPORT(a) a
#       define SWIGIMPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;                 
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;	
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGIMPORT(void *)           SWIG_TypeCast(swig_type_info *, void *);
SWIGIMPORT(swig_type_info *) SWIG_TypeDynamicCast(swig_type_info *, void **);
SWIGIMPORT(const char *)     SWIG_TypeName(const swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGIMPORT(void)             SWIG_TypeClientData(swig_type_info *, void *);

#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      if (tc->clientdata) ti->clientdata = tc->clientdata;	
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;  /**/
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;  /**/
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Cast a pointer up an inheritance hierarchy */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Dynamic pointer casting. Down an inheritance hierarchy */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) 
{
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
     ty = (*ty->dcast)(ptr);
     if (ty) lastty = ty;
  }
  return lastty;
}

/* Return the name associated with this type */
SWIGRUNTIME(const char *)
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata == clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
	if ((strcmp(tc->name, equiv->name) == 0))
	  SWIG_TypeClientData(tc,clientdata);
	tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}
#endif

#ifdef __cplusplus
}

#endif

/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY  5

/* Flags for pointer conversion */

#define SWIG_POINTER_EXCEPTION     0x1
#define SWIG_POINTER_DISOWN        0x2

/* Exception handling in wrappers */
#define SWIG_fail   goto fail

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

#ifdef SWIG_NOINCLUDE

SWIGEXPORT(PyObject *)        SWIG_newvarlink(void);
SWIGEXPORT(void)              SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGEXPORT(int)               SWIG_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGEXPORT(int)               SWIG_ConvertPacked(PyObject *, void *, int sz, swig_type_info *, int);
SWIGEXPORT(char *)            SWIG_PackData(char *c, void *, int);
SWIGEXPORT(char *)            SWIG_UnpackData(char *c, void *, int);
SWIGEXPORT(PyObject *)        SWIG_NewPointerObj(void *, swig_type_info *,int own);
SWIGEXPORT(PyObject *)        SWIG_NewPackedObj(void *, int sz, swig_type_info *);
SWIGEXPORT(void)              SWIG_InstallConstants(PyObject *d, swig_const_info constants[]);
#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  (char *)"swigvarlink",                      /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  int i;
  unsigned char *u = (unsigned char *) ptr;
  register unsigned char uu;
  for (i = 0; i < sz; i++,u++) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu = 0;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  int i;
  for (i = 0; i < sz; i++, u++) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;
  static PyObject *SWIG_this = 0;
  int    newref = 0;
  PyObject  *pyobj = 0;

  if (!obj) return 0;
  if (obj == Py_None) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  }  
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) { Py_DECREF(obj); }
      return 0;
    } else {
      if (newref) { Py_DECREF(obj); }
      goto type_error;
    }
  }
  c++;
  c = SWIG_UnpackData(c,ptr,sizeof(void *));
  if (newref) { Py_DECREF(obj); }
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*) *ptr);
  }

  if ((pyobj) && (flags & SWIG_POINTER_DISOWN)) {
      PyObject *zero = PyInt_FromLong(0);
      PyObject_SetAttrString(pyobj,(char*)"thisown",zero);
      Py_DECREF(zero);
  }
  return 0;

type_error:
  if (flags & SWIG_POINTER_EXCEPTION) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Convert a packed value value */
SWIGRUNTIME(int)
SWIG_ConvertPacked(PyObject *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;

  if ((!obj) || (!PyString_Check(obj))) goto type_error;
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
  }
  return 0;

type_error:

  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_NewPointerObj(void *ptr, swig_type_info *type, int own) {
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, (char *) type->name, NULL);
#else
  {
    char result[1024];
    char *r = result;
    *(r++) = '_';
    r = SWIG_PackData(r,&ptr,sizeof(void *));
    strcpy(r,type->name);
    robj = PyString_FromString(result);
  }
#endif
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyObject *inst;
    PyObject *args = Py_BuildValue((char*)"(O)", robj);
    Py_DECREF(robj);
    inst = PyObject_CallObject((PyObject *) type->clientdata, args);
    Py_DECREF(args);
    if (inst) {
      if (own) {
	PyObject *n = PyInt_FromLong(1);
	PyObject_SetAttrString(inst,(char*)"thisown",n);
	Py_DECREF(n);
      }
      robj = inst;
    }
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  return PyString_FromString(result);
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype,0);
      break;
    case SWIG_PY_BINARY:
      obj = SWIG_NewPackedObj(constants[i].pvalue, constants[i].lvalue, *(constants[i].ptype));
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

#ifdef __cplusplus
}
#endif








/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_AAChain swig_types[0] 
#define  SWIGTYPE_p_Ligand swig_types[1] 
#define  SWIGTYPE_p_pairTdouble_string_t swig_types[2] 
#define  SWIGTYPE_p_vectorTint_t swig_types[3] 
#define  SWIGTYPE_p_string swig_types[4] 
#define  SWIGTYPE_p_SCREAM_ATOM swig_types[5] 
#define  SWIGTYPE_p_ScreamAtomV swig_types[6] 
#define  SWIGTYPE_p_AARotamer swig_types[7] 
#define  SWIGTYPE_p_Rotamer swig_types[8] 
#define  SWIGTYPE_p_Protein swig_types[9] 
#define  SWIGTYPE_p_RotConnInfo swig_types[10] 
#define  SWIGTYPE_p_ostream swig_types[11] 
static swig_type_info *swig_types[13];

/* -------- TYPES TABLE (END) -------- */


/*-----------------------------------------------
              @(target):= _Py_Protein.so
  ------------------------------------------------*/
#define SWIG_init    init_Py_Protein

#define SWIG_name    "_Py_Protein"


#include "sc_Protein.hpp"


#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_new_Protein__SWIG_0(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_Protein")) goto fail;
    result = (Protein *)new Protein();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Protein, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_Protein__SWIG_1(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = 0 ;
    Protein *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:new_Protein",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1 == NULL) {
        PyErr_SetString(PyExc_TypeError,"null reference"); SWIG_fail; 
    }
    result = (Protein *)new Protein((Protein const &)*arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Protein, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_Protein__SWIG_2(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    ScreamAtomV *arg1 = 0 ;
    Protein *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:new_Protein",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_ScreamAtomV,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1 == NULL) {
        PyErr_SetString(PyExc_TypeError,"null reference"); SWIG_fail; 
    }
    result = (Protein *)new Protein(*arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Protein, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_Protein(PyObject *self, PyObject *args) {
    int argc;
    PyObject *argv[2];
    int ii;
    
    argc = PyObject_Length(args);
    for (ii = 0; (ii < argc) && (ii < 1); ii++) {
        argv[ii] = PyTuple_GetItem(args,ii);
    }
    if (argc == 0) {
        return _wrap_new_Protein__SWIG_0(self,args);
    }
    if (argc == 1) {
        int _v;
        {
            void *ptr;
            if (SWIG_ConvertPtr(argv[0], (void **) &ptr, SWIGTYPE_p_Protein, 0) == -1) {
                _v = 0;
                PyErr_Clear();
            }else {
                _v = 1;
            }
        }
        if (_v) {
            return _wrap_new_Protein__SWIG_1(self,args);
        }
    }
    if (argc == 1) {
        int _v;
        {
            void *ptr;
            if (SWIG_ConvertPtr(argv[0], (void **) &ptr, SWIGTYPE_p_ScreamAtomV, 0) == -1) {
                _v = 0;
                PyErr_Clear();
            }else {
                _v = 1;
            }
        }
        if (_v) {
            return _wrap_new_Protein__SWIG_2(self,args);
        }
    }
    
    PyErr_SetString(PyExc_TypeError,"No matching function for overloaded 'new_Protein'");
    return NULL;
}


static PyObject *_wrap_delete_Protein(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_Protein",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    delete arg1;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_get_AAChain(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    string arg2 ;
    AAChain *result;
    string *argp2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Protein_get_AAChain",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &argp2, SWIGTYPE_p_string,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg2 = *argp2; 
    result = (AAChain *)((Protein const *)arg1)->get_AAChain(arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_AAChain, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_get_Ligand(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    Ligand *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Protein_get_Ligand",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Ligand *)((Protein const *)arg1)->get_Ligand();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Ligand, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_get_res_type(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    string arg2 ;
    int arg3 ;
    string result;
    string *argp2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOi:Protein_get_res_type",&obj0,&obj1,&arg3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &argp2, SWIGTYPE_p_string,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg2 = *argp2; 
    result = ((Protein const *)arg1)->get_res_type(arg2,arg3);
    
    {
        string * resultptr;
        resultptr = new string((string &) result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_string, 1);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_get_sc_atoms(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    string arg2 ;
    int arg3 ;
    ScreamAtomV result;
    string *argp2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOi:Protein_get_sc_atoms",&obj0,&obj1,&arg3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &argp2, SWIGTYPE_p_string,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg2 = *argp2; 
    result = ((Protein const *)arg1)->get_sc_atoms(arg2,arg3);
    
    {
        ScreamAtomV * resultptr;
        resultptr = new ScreamAtomV((ScreamAtomV &) result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_ScreamAtomV, 1);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_get_variable_atoms(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    RotConnInfo *arg2 = (RotConnInfo *) 0 ;
    ScreamAtomV result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Protein_get_variable_atoms",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_RotConnInfo,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = ((Protein const *)arg1)->get_variable_atoms(arg2);
    
    {
        ScreamAtomV * resultptr;
        resultptr = new ScreamAtomV((ScreamAtomV &) result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_ScreamAtomV, 1);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_getAtomList__SWIG_0(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    ScreamAtomV *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Protein_getAtomList",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        ScreamAtomV &_result_ref = (arg1)->getAtomList();
        result = (ScreamAtomV *) &_result_ref;
    }
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_ScreamAtomV, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_getAtomList__SWIG_1(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    ScreamAtomV *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Protein_getAtomList",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        ScreamAtomV const &_result_ref = ((Protein const *)arg1)->getAtomList();
        result = (ScreamAtomV *) &_result_ref;
    }
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_ScreamAtomV, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_getAtomList(PyObject *self, PyObject *args) {
    int argc;
    PyObject *argv[2];
    int ii;
    
    argc = PyObject_Length(args);
    for (ii = 0; (ii < argc) && (ii < 1); ii++) {
        argv[ii] = PyTuple_GetItem(args,ii);
    }
    if (argc == 1) {
        int _v;
        {
            void *ptr;
            if (SWIG_ConvertPtr(argv[0], (void **) &ptr, SWIGTYPE_p_Protein, 0) == -1) {
                _v = 0;
                PyErr_Clear();
            }else {
                _v = 1;
            }
        }
        if (_v) {
            return _wrap_Protein_getAtomList__SWIG_0(self,args);
        }
    }
    if (argc == 1) {
        int _v;
        {
            void *ptr;
            if (SWIG_ConvertPtr(argv[0], (void **) &ptr, SWIGTYPE_p_Protein, 0) == -1) {
                _v = 0;
                PyErr_Clear();
            }else {
                _v = 1;
            }
        }
        if (_v) {
            return _wrap_Protein_getAtomList__SWIG_1(self,args);
        }
    }
    
    PyErr_SetString(PyExc_TypeError,"No matching function for overloaded 'Protein_getAtomList'");
    return NULL;
}


static PyObject *_wrap_Protein_getAtom(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    int arg2 ;
    SCREAM_ATOM *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:Protein_getAtom",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (SCREAM_ATOM *)((Protein const *)arg1)->getAtom(arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_SCREAM_ATOM, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_getTheseAtoms(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    vector<int > *arg2 = 0 ;
    ScreamAtomV result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Protein_getTheseAtoms",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_vectorTint_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg2 == NULL) {
        PyErr_SetString(PyExc_TypeError,"null reference"); SWIG_fail; 
    }
    result = ((Protein const *)arg1)->getTheseAtoms(*arg2);
    
    {
        ScreamAtomV * resultptr;
        resultptr = new ScreamAtomV((ScreamAtomV &) result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_ScreamAtomV, 1);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_totalComponents(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Protein_totalComponents",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)((Protein const *)arg1)->totalComponents();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_ntrlRotamerPlacement(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    string arg2 ;
    int arg3 ;
    AARotamer *arg4 = (AARotamer *) 0 ;
    int result;
    string *argp2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj3 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOiO:Protein_ntrlRotamerPlacement",&obj0,&obj1,&arg3,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &argp2, SWIGTYPE_p_string,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg2 = *argp2; 
    if ((SWIG_ConvertPtr(obj3,(void **) &arg4, SWIGTYPE_p_AARotamer,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)(arg1)->ntrlRotamerPlacement(arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_conformerPlacement(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    Rotamer *arg2 = (Rotamer *) 0 ;
    RotConnInfo *arg3 = (RotConnInfo *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:Protein_conformerPlacement",&obj0,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Rotamer,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_RotConnInfo,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)(arg1)->conformerPlacement(arg2,arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_conformerExtraction(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    RotConnInfo *arg2 = (RotConnInfo *) 0 ;
    Rotamer *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Protein_conformerExtraction",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_RotConnInfo,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Rotamer *)(arg1)->conformerExtraction(arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Rotamer, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_mutation(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    string arg2 ;
    int arg3 ;
    string arg4 ;
    int result;
    string *argp2 ;
    string *argp4 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj3 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOiO:Protein_mutation",&obj0,&obj1,&arg3,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &argp2, SWIGTYPE_p_string,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg2 = *argp2; 
    if ((SWIG_ConvertPtr(obj3,(void **) &argp4, SWIGTYPE_p_string,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg4 = *argp4; 
    result = (int)(arg1)->mutation(arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_sc_clash__SWIG_0(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    string arg2 ;
    int arg3 ;
    double result;
    string *argp2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOi:Protein_sc_clash",&obj0,&obj1,&arg3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &argp2, SWIGTYPE_p_string,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg2 = *argp2; 
    result = (double)((Protein const *)arg1)->sc_clash(arg2,arg3);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_sc_clash__SWIG_1(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    string arg2 ;
    int arg3 ;
    ScreamAtomV *arg4 = 0 ;
    double result;
    string *argp2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj3 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOiO:Protein_sc_clash",&obj0,&obj1,&arg3,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &argp2, SWIGTYPE_p_string,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg2 = *argp2; 
    if ((SWIG_ConvertPtr(obj3,(void **) &arg4, SWIGTYPE_p_ScreamAtomV,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg4 == NULL) {
        PyErr_SetString(PyExc_TypeError,"null reference"); SWIG_fail; 
    }
    result = (double)((Protein const *)arg1)->sc_clash(arg2,arg3,*arg4);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_sc_clash(PyObject *self, PyObject *args) {
    int argc;
    PyObject *argv[5];
    int ii;
    
    argc = PyObject_Length(args);
    for (ii = 0; (ii < argc) && (ii < 4); ii++) {
        argv[ii] = PyTuple_GetItem(args,ii);
    }
    if (argc == 3) {
        int _v;
        {
            void *ptr;
            if (SWIG_ConvertPtr(argv[0], (void **) &ptr, SWIGTYPE_p_Protein, 0) == -1) {
                _v = 0;
                PyErr_Clear();
            }else {
                _v = 1;
            }
        }
        if (_v) {
            {
                void *ptr;
                if (SWIG_ConvertPtr(argv[1], (void **) &ptr, SWIGTYPE_p_string, 0) == -1) {
                    _v = 0;
                    PyErr_Clear();
                }else {
                    _v = 1;
                }
            }
            if (_v) {
                {
                    _v = (PyInt_Check(argv[2]) || PyLong_Check(argv[2])) ? 1 : 0;
                }
                if (_v) {
                    return _wrap_Protein_sc_clash__SWIG_0(self,args);
                }
            }
        }
    }
    if (argc == 4) {
        int _v;
        {
            void *ptr;
            if (SWIG_ConvertPtr(argv[0], (void **) &ptr, SWIGTYPE_p_Protein, 0) == -1) {
                _v = 0;
                PyErr_Clear();
            }else {
                _v = 1;
            }
        }
        if (_v) {
            {
                void *ptr;
                if (SWIG_ConvertPtr(argv[1], (void **) &ptr, SWIGTYPE_p_string, 0) == -1) {
                    _v = 0;
                    PyErr_Clear();
                }else {
                    _v = 1;
                }
            }
            if (_v) {
                {
                    _v = (PyInt_Check(argv[2]) || PyLong_Check(argv[2])) ? 1 : 0;
                }
                if (_v) {
                    {
                        void *ptr;
                        if (SWIG_ConvertPtr(argv[3], (void **) &ptr, SWIGTYPE_p_ScreamAtomV, 0) == -1) {
                            _v = 0;
                            PyErr_Clear();
                        }else {
                            _v = 1;
                        }
                    }
                    if (_v) {
                        return _wrap_Protein_sc_clash__SWIG_1(self,args);
                    }
                }
            }
        }
    }
    
    PyErr_SetString(PyExc_TypeError,"No matching function for overloaded 'Protein_sc_clash'");
    return NULL;
}


static PyObject *_wrap_Protein_conformer_clash__SWIG_0(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    RotConnInfo *arg2 = (RotConnInfo *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Protein_conformer_clash",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_RotConnInfo,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double)((Protein const *)arg1)->conformer_clash(arg2);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_conformer_clash__SWIG_1(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    RotConnInfo *arg2 = (RotConnInfo *) 0 ;
    ScreamAtomV *arg3 = 0 ;
    double result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:Protein_conformer_clash",&obj0,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_RotConnInfo,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_ScreamAtomV,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg3 == NULL) {
        PyErr_SetString(PyExc_TypeError,"null reference"); SWIG_fail; 
    }
    result = (double)((Protein const *)arg1)->conformer_clash(arg2,*arg3);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_conformer_clash(PyObject *self, PyObject *args) {
    int argc;
    PyObject *argv[4];
    int ii;
    
    argc = PyObject_Length(args);
    for (ii = 0; (ii < argc) && (ii < 3); ii++) {
        argv[ii] = PyTuple_GetItem(args,ii);
    }
    if (argc == 2) {
        int _v;
        {
            void *ptr;
            if (SWIG_ConvertPtr(argv[0], (void **) &ptr, SWIGTYPE_p_Protein, 0) == -1) {
                _v = 0;
                PyErr_Clear();
            }else {
                _v = 1;
            }
        }
        if (_v) {
            {
                void *ptr;
                if (SWIG_ConvertPtr(argv[1], (void **) &ptr, SWIGTYPE_p_RotConnInfo, 0) == -1) {
                    _v = 0;
                    PyErr_Clear();
                }else {
                    _v = 1;
                }
            }
            if (_v) {
                return _wrap_Protein_conformer_clash__SWIG_0(self,args);
            }
        }
    }
    if (argc == 3) {
        int _v;
        {
            void *ptr;
            if (SWIG_ConvertPtr(argv[0], (void **) &ptr, SWIGTYPE_p_Protein, 0) == -1) {
                _v = 0;
                PyErr_Clear();
            }else {
                _v = 1;
            }
        }
        if (_v) {
            {
                void *ptr;
                if (SWIG_ConvertPtr(argv[1], (void **) &ptr, SWIGTYPE_p_RotConnInfo, 0) == -1) {
                    _v = 0;
                    PyErr_Clear();
                }else {
                    _v = 1;
                }
            }
            if (_v) {
                {
                    void *ptr;
                    if (SWIG_ConvertPtr(argv[2], (void **) &ptr, SWIGTYPE_p_ScreamAtomV, 0) == -1) {
                        _v = 0;
                        PyErr_Clear();
                    }else {
                        _v = 1;
                    }
                }
                if (_v) {
                    return _wrap_Protein_conformer_clash__SWIG_1(self,args);
                }
            }
        }
    }
    
    PyErr_SetString(PyExc_TypeError,"No matching function for overloaded 'Protein_conformer_clash'");
    return NULL;
}


static PyObject *_wrap_Protein_sc_CRMS(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    string arg2 ;
    int arg3 ;
    Protein *arg4 = (Protein *) 0 ;
    double result;
    string *argp2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj3 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOiO:Protein_sc_CRMS",&obj0,&obj1,&arg3,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &argp2, SWIGTYPE_p_string,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg2 = *argp2; 
    if ((SWIG_ConvertPtr(obj3,(void **) &arg4, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double)((Protein const *)arg1)->sc_CRMS(arg2,arg3,arg4);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_conformer_CRMS(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    Protein *arg2 = (Protein *) 0 ;
    RotConnInfo *arg3 = (RotConnInfo *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:Protein_conformer_CRMS",&obj0,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_RotConnInfo,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double)((Protein const *)arg1)->conformer_CRMS(arg2,arg3);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_max_atom_dist_on_SC(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    string arg2 ;
    int arg3 ;
    Protein *arg4 = (Protein *) 0 ;
    pair<double,string > result;
    string *argp2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj3 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOiO:Protein_max_atom_dist_on_SC",&obj0,&obj1,&arg3,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &argp2, SWIGTYPE_p_string,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg2 = *argp2; 
    if ((SWIG_ConvertPtr(obj3,(void **) &arg4, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = ((Protein const *)arg1)->max_atom_dist_on_SC(arg2,arg3,arg4);
    
    {
        pair<double,string > * resultptr;
        resultptr = new pair<double,string >((pair<double,string > &) result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_pairTdouble_string_t, 1);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_fix_entire_atom_list_ordering(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Protein_fix_entire_atom_list_ordering",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    (arg1)->fix_entire_atom_list_ordering();
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_fix_toggle(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    bool arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Protein_fix_toggle",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    arg2 = PyInt_AsLong(obj1) ? true : false;
    if (PyErr_Occurred()) SWIG_fail;
    (arg1)->fix_toggle(arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_fix_sc_toggle(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    bool arg2 ;
    int arg3 ;
    string arg4 ;
    string *argp4 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj3 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOiO:Protein_fix_sc_toggle",&obj0,&obj1,&arg3,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    arg2 = PyInt_AsLong(obj1) ? true : false;
    if (PyErr_Occurred()) SWIG_fail;
    if ((SWIG_ConvertPtr(obj3,(void **) &argp4, SWIGTYPE_p_string,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg4 = *argp4; 
    (arg1)->fix_sc_toggle(arg2,arg3,arg4);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_append_to_filehandle(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    ostream *arg2 = (ostream *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Protein_append_to_filehandle",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_ostream,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    ((Protein const *)arg1)->append_to_filehandle(arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_pdb_append_to_filehandle(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    ostream *arg2 = (ostream *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Protein_pdb_append_to_filehandle",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_ostream,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    ((Protein const *)arg1)->pdb_append_to_filehandle(arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_print_bgf_file(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    ostream *arg2 = (ostream *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Protein_print_bgf_file",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_ostream,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    ((Protein const *)arg1)->print_bgf_file(arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_print_Me(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Protein_print_Me",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    ((Protein const *)arg1)->print_Me();
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Protein_print_ordered_by_n(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Protein *arg1 = (Protein *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Protein_print_ordered_by_n",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Protein,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    ((Protein const *)arg1)->print_ordered_by_n();
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject * Protein_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_Protein, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyMethodDef SwigMethods[] = {
	 { (char *)"new_Protein", _wrap_new_Protein, METH_VARARGS },
	 { (char *)"delete_Protein", _wrap_delete_Protein, METH_VARARGS },
	 { (char *)"Protein_get_AAChain", _wrap_Protein_get_AAChain, METH_VARARGS },
	 { (char *)"Protein_get_Ligand", _wrap_Protein_get_Ligand, METH_VARARGS },
	 { (char *)"Protein_get_res_type", _wrap_Protein_get_res_type, METH_VARARGS },
	 { (char *)"Protein_get_sc_atoms", _wrap_Protein_get_sc_atoms, METH_VARARGS },
	 { (char *)"Protein_get_variable_atoms", _wrap_Protein_get_variable_atoms, METH_VARARGS },
	 { (char *)"Protein_getAtomList", _wrap_Protein_getAtomList, METH_VARARGS },
	 { (char *)"Protein_getAtom", _wrap_Protein_getAtom, METH_VARARGS },
	 { (char *)"Protein_getTheseAtoms", _wrap_Protein_getTheseAtoms, METH_VARARGS },
	 { (char *)"Protein_totalComponents", _wrap_Protein_totalComponents, METH_VARARGS },
	 { (char *)"Protein_ntrlRotamerPlacement", _wrap_Protein_ntrlRotamerPlacement, METH_VARARGS },
	 { (char *)"Protein_conformerPlacement", _wrap_Protein_conformerPlacement, METH_VARARGS },
	 { (char *)"Protein_conformerExtraction", _wrap_Protein_conformerExtraction, METH_VARARGS },
	 { (char *)"Protein_mutation", _wrap_Protein_mutation, METH_VARARGS },
	 { (char *)"Protein_sc_clash", _wrap_Protein_sc_clash, METH_VARARGS },
	 { (char *)"Protein_conformer_clash", _wrap_Protein_conformer_clash, METH_VARARGS },
	 { (char *)"Protein_sc_CRMS", _wrap_Protein_sc_CRMS, METH_VARARGS },
	 { (char *)"Protein_conformer_CRMS", _wrap_Protein_conformer_CRMS, METH_VARARGS },
	 { (char *)"Protein_max_atom_dist_on_SC", _wrap_Protein_max_atom_dist_on_SC, METH_VARARGS },
	 { (char *)"Protein_fix_entire_atom_list_ordering", _wrap_Protein_fix_entire_atom_list_ordering, METH_VARARGS },
	 { (char *)"Protein_fix_toggle", _wrap_Protein_fix_toggle, METH_VARARGS },
	 { (char *)"Protein_fix_sc_toggle", _wrap_Protein_fix_sc_toggle, METH_VARARGS },
	 { (char *)"Protein_append_to_filehandle", _wrap_Protein_append_to_filehandle, METH_VARARGS },
	 { (char *)"Protein_pdb_append_to_filehandle", _wrap_Protein_pdb_append_to_filehandle, METH_VARARGS },
	 { (char *)"Protein_print_bgf_file", _wrap_Protein_print_bgf_file, METH_VARARGS },
	 { (char *)"Protein_print_Me", _wrap_Protein_print_Me, METH_VARARGS },
	 { (char *)"Protein_print_ordered_by_n", _wrap_Protein_print_ordered_by_n, METH_VARARGS },
	 { (char *)"Protein_swigregister", Protein_swigregister, METH_VARARGS },
	 { NULL, NULL }
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_AAChain[] = {{"_p_AAChain", 0, "AAChain *", 0},{"_p_AAChain"},{0}};
static swig_type_info _swigt__p_Ligand[] = {{"_p_Ligand", 0, "Ligand *", 0},{"_p_Ligand"},{0}};
static swig_type_info _swigt__p_pairTdouble_string_t[] = {{"_p_pairTdouble_string_t", 0, "pair<double,string > *", 0},{"_p_pairTdouble_string_t"},{0}};
static swig_type_info _swigt__p_vectorTint_t[] = {{"_p_vectorTint_t", 0, "vector<int > *", 0},{"_p_vectorTint_t"},{0}};
static swig_type_info _swigt__p_string[] = {{"_p_string", 0, "string *", 0},{"_p_string"},{0}};
static swig_type_info _swigt__p_SCREAM_ATOM[] = {{"_p_SCREAM_ATOM", 0, "SCREAM_ATOM *", 0},{"_p_SCREAM_ATOM"},{0}};
static swig_type_info _swigt__p_ScreamAtomV[] = {{"_p_ScreamAtomV", 0, "ScreamAtomV *", 0},{"_p_ScreamAtomV"},{0}};
static swig_type_info _swigt__p_AARotamer[] = {{"_p_AARotamer", 0, "AARotamer *", 0},{"_p_AARotamer"},{0}};
static swig_type_info _swigt__p_Rotamer[] = {{"_p_Rotamer", 0, "Rotamer *", 0},{"_p_Rotamer"},{0}};
static swig_type_info _swigt__p_Protein[] = {{"_p_Protein", 0, "Protein *", 0},{"_p_Protein"},{0}};
static swig_type_info _swigt__p_RotConnInfo[] = {{"_p_RotConnInfo", 0, "RotConnInfo *", 0},{"_p_RotConnInfo"},{0}};
static swig_type_info _swigt__p_ostream[] = {{"_p_ostream", 0, "ostream *", 0},{"_p_ostream"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_AAChain, 
_swigt__p_Ligand, 
_swigt__p_pairTdouble_string_t, 
_swigt__p_vectorTint_t, 
_swigt__p_string, 
_swigt__p_SCREAM_ATOM, 
_swigt__p_ScreamAtomV, 
_swigt__p_AARotamer, 
_swigt__p_Rotamer, 
_swigt__p_Protein, 
_swigt__p_RotConnInfo, 
_swigt__p_ostream, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
{0}};

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) SWIG_init(void) {
    static PyObject *SWIG_globals = 0; 
    static int       typeinit = 0;
    PyObject *m, *d;
    int       i;
    if (!SWIG_globals) SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule((char *) SWIG_name, SwigMethods);
    d = PyModule_GetDict(m);
    
    if (!typeinit) {
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }
        typeinit = 1;
    }
    SWIG_InstallConstants(d,swig_const_table);
    
}

